### ISSUE TITLE
example app is not working with a simple curl

### ISSUE THREAD

**Issue by jcollum** [macedigital/express-xml-bodyparser#11]
I took your sample app and stripped it down to basics: 

```
  var app, express, http, server, xmlparser;
  express = require('express');
  app = express();
  http = require('http');
  server = http.createServer(app);

  xmlparser = require('express-xml-bodyparser');
  app.use(xmlparser());

  app.post('/xml', function(req, res, next) {
    var _ref, _ref1;
    if (((_ref = req.body) != null ? _ref.length : void 0) > 0) {
      res.send('OK!');
    } else {
      res.send('Not OK :(');
    }
    console.log("post body length " + (((_ref1 = req.body) != null ? _ref1.length : void 0) || 0));
    return res.end();
  });

  server.listen(1337);
```

Runs fine. But when I send it a chunk of XML via CURL I get nothing: 

```
10:17 ~ $ curl -X POST -H "Content-Type: text/xml" -d '<?xml version=\"1.0\" encoding=\"UTF-8\"?><stuff>Hello?</stuff>' http://localhost:1337/xml
Not OK :(
10:17 ~ $ curl -X POST -H "Content-Type: application/xml" -d '<?xml version=\"1.0\" encoding=\"UTF-8\"?><stuff>Hello?</stuff>' http://localhost:1337/xml
Not OK :(
```

When I send the same content to a simple server using just the http module, it works fine: 

```
$ curl -X POST -H "Content-Type: application/xml" -d '<?xml version=\"1.0\" encoding=\"UTF-8\"?><stuff>Hello?</stuff>' http://localhost:3000
post received: <?xml version=\"1.0\" encoding=\"UTF-8\"?><stuff>Hello?</stuff>
```

(The server code is simple, you can see it here: http://stackoverflow.com/a/12007627/30946) 

I can't see any way to strip the sample down further, so either the code isn't working right or I'm doing something wrong. Suggestions? Bug?

**Comment by macedigital** [comment]
@jcollum No, it is not a bug in the parser.

In your example, you use the wrong method for testing whether `req.body` contains data. Calling `req.body.length` is `undefined` (unless someone sends XML like this: `<length>5</length>`).

Also, `req.body` contains the parsed XML data structure (which is an Object), not the data sent to the server. If you need access to posted data as a string, use the `req.rawBody` property.

For a working example, see https://gist.github.com/macedigital/6b71b9547dd4421d8724. I made only minor modifications to your original snippet.
