### ISSUE TITLE
Is it still no longer advisable to have xml2js operate in async=true mode?

### ISSUE THREAD

**Issue by samskeller** [macedigital/express-xml-bodyparser#16]
In the README for this repo, you give the following warning:
```
IMPORTANT: Currently, it is not advisable to operate xml2js in async=true mode. Unless you can absolutely trust input data (which you should not), certain types of invalid XML will throw uncaught exceptions. See https://github.com/Leonidas-from-XIV/node-xml2js/issues/232 for progress on this issue. Until then, the default option is set to async=false.
```
However, as far as I can tell, the issue being referenced has been resolved and it's no longer unsafe to operate `xml2js` in `async=true` mode. Is this correct? If so, I can create a PR for this README to remove the warning!

Thanks!

**Comment by macedigital** [comment]
@samskeller Good catch 👍 
I'll have to double-check, but it looks like `async=true` issues have been resolved. Your PR is welcome 😄

**Comment by samskeller** [comment]
Great, thanks @macedigital! I'll create a PR and tag you on it

**Comment by macedigital** [comment]
Issue is fixed.
