### ISSUE TITLE
Is this works with gzip requests?

### ISSUE THREAD

**Issue by brunodomenici** [macedigital/express-xml-bodyparser#18]
Hi,

I need to receive POST requests with gziped XMLs. In my tests, I'm receiving:

`{"message":"Non-whitespace before first tag.\nLine: 0\nColumn: 1\nChar: \u001f","status":400}`

I suspect that this message is coming from xml2js.

In my project we use compression middleware also, I don't know with this could interfere.

Thank you.

**Comment by macedigital** [comment]
@brunodomenici In your case, you'll need to add a middleware that de-compresses the request before passing it on to the xml-parser. Unfortunately, I don't know of pre-made ones you could install via npm.

If you need this feature, have a look at [unzip-post-body-with-node-express](https://stackoverflow.com/questions/14194864/unzip-post-body-with-node-express#answer-14198427) and [how-can-i-gunzip-post-request-data-in-express](https://stackoverflow.com/questions/15783208/how-can-i-gunzip-post-request-data-in-express#question).

**Comment by brunodomenici** [comment]
Alright, thanks a lot and sorry for delay.
