### ISSUE TITLE
Consider removing shrinkwrap file

### ISSUE THREAD

**Issue by fiznool** [macedigital/express-xml-bodyparser#9]
I've never seen shrinkwrap used for libraries before, AFAIK it is meant for top-level apps.

Is there a reason for its inclusion in the project? Could it be removed?

**Comment by macedigital** [comment]
It will be removed in the next release. I added it, after issue #6 emerged, so xml2js would definitely be downgraded to v0.4.5. But thanks to your help its not needed anymore.

**Comment by macedigital** [comment]
@fiznool I just pushed a new release without a `shrinkwrap.json` file. Thanks for your support!

**Comment by fiznool** [comment]
:+1:
